name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the ordinary workflow artifact containing the built site
        required: true
        type: string

permissions: {}

jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs['page-url'] }}

    steps:
      - name: Deploy site
        id: deployment
        uses: SayakMukhopadhyay/github-actions/deploy-pages-artifact@v1
        with:
          github-token: ${{ github.token }}
          source-repository: ${{ github.repository }}
          source-run-id: ${{ github.run_id }}
          artifact-name: ${{ inputs.artifact-name }}
