name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE*'
      - '.idea/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    name: CI
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml
    with:
      publish-artifact: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}

  deploy-pages:
    name: Deploy Pages
    if: >-
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    needs:
      - ci
    concurrency:
      group: ${{ github.workflow }}-pages
      cancel-in-progress: false
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy-pages.yml
    with:
      artifact-name: site-greybody-games
